"""Add user social login

Revision ID: f39a585dce63
Revises: 38d84cab7ded
Create Date: 2024-12-10 12:07:58.798289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f39a585dce63'
down_revision: Union[str, None] = '38d84cab7ded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_member', sa.Column('social_provider', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_member', 'social_provider')
    # ### end Alembic commands ###
