"""Add chat room


Revision ID: 1eecd94683e1
Revises: d9a592c0c8ca
Create Date: 2024-12-12 14:44:07.433910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eecd94683e1'
down_revision: Union[str, None] = 'd9a592c0c8ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chat_messages', sa.Column('chat_room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat_messages', 'chat_room', ['chat_room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_column('chat_messages', 'chat_room_id')
    op.drop_table('chat_room')
    # ### end Alembic commands ###
